version: "3"

services:
  unbound-helper:
    container_name: unbound-helper
    image: alpinelinux/unbound
    restart: on-failure
    entrypoint: []
    command: chown -R unbound:unbound /var/log/unbound
    volumes:
      - './data/unbound/logs:/var/log/unbound:rw'

  unbound:
    container_name: unbound
    image: alpinelinux/unbound
    restart: unless-stopped
    depends_on:
      - unbound-helper
    ports:
      - "127.0.0.1:5335:5335/tcp"
      - "127.0.0.1:5335:5335/udp"
      - "127.0.0.1:8953:8953/tcp"
    volumes:
      - './data/unbound/logs:/var/log/unbound:rw'
      - './data/unbound/etc:/etc/unbound:rw'

  unbound-exporter:
    container_name: unbound-exporter
    build:
      context: unbound-exporter
    restart: unless-stopped
    depends_on:
      - unbound
    environment:
      UNBOUND_URI: tcp://unbound:8953
      UNBOUND_SERVER_CERT_PATH: /etc/unbound/unbound_server.pem
      UNBOUND_CONTROL_CERT_PATH: /etc/unbound/unbound_control.pem
      UNBOUND_CONTROL_KEY_PATH: /etc/unbound/unbound_control.key
    volumes:
      - './data/unbound/etc:/etc/unbound:ro'
    ports:
      - "9167:9167/tcp"

  pihole:
    container_name: pihole
    image: pihole/pihole:2023.02.2
    restart: unless-stopped
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9080:80/tcp"
    environment:
      TZ: 'Europe/Bucharest'
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_DNS_: unbound#5335;unbound#5335
      IPv6: false
    volumes:
      - './data/pihole/etc:/etc/pihole:rw'
      - './data/pihole/logs:/var/log/pihole:rw'
      - './data/dnsmasq:/etc/dnsmasq.d:rw'
    secrets:
      - pihole_password

  pihole-exporter:
    container_name: pihole-exporter
    build:
      context: pihole-exporter
    restart: unless-stopped
    depends_on:
      - pihole
    ports:
      - "127.0.0.1:9168:9168/tcp"
    environment:
      PORT: 9168
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PASSWORD_FILE: /run/secrets/pihole_password
    secrets:
      - pihole_password

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.42.0
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    # network_mode: host
    depends_on:
      - unbound-exporter
      - pihole-exporter
    ports:
      - "9090:9090/tcp"
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:rw'
      - './data/prometheus:/prometheus:rw'

  loki:
    container_name: loki
    image: grafana/loki:2.7.3
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - './data/loki:/loki:rw'
      - './loki.yml:/etc/loki/local-config.yaml'

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.3
    restart: unless-stopped
    depends_on:
      - loki
      - unbound
    volumes:
      - './data/unbound/logs:/var/log/unbound:ro'
      - './promtail.yml:/etc/promtail/config.yml'
    command: -config.file=/etc/promtail/config.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.3
    restart: unless-stopped
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - ./data/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana/lib:/var/lib/grafana

secrets:
   pihole_password:
     file: pihole_password.txt
